ii/ol/config/routes.rb
Rails.application.routes.draw do
  root 'accueil#index'
  post 'session/create'
  delete 'session/destroy'
  get 'accueil/index'
  get 'accueil/auctions'
  get 'accueil/agents'
  get 'accueil/reviews'
  get 'accueil/about'

  #Users controller
  #get 'users/new', :as => "new_users"

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ii/ol/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ii/ol/app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
  	#validates :name, presence: true, length: { maximum: 50 }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
	has_secure_password
  	validates :email, uniqueness: true, presence: true
end

ii/ol/app/controllers/accueil_controller.rb
class AccueilController < ApplicationController
  skip_before_action :require_valid_user!

  def index
  end

  def auctions
  end

  def agents
  end

  def reviews
  end

  def about
  end
end

ii/ol/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  	before_action :require_valid_user!

	  def current_user
	    if !session[:user_id].blank?
	      @user ||= User.find(session[:user_id])
	    end
	  end

	  def require_valid_user!
	    if current_user.nil?
	      flash[:error] = 'You must be logged in to access that page!'
	      redirect_to login_path
	    end
	  end

end

ii/ol/app/controllers/session_controller.rb
class SessionController < ApplicationController

include SessionHelper
skip_before_action :require_valid_user!, except: [:logout]

  def create
    reset_session
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = 'Succesful login'
      redirect_to root_path
    else
      flash[:error] = 'Invalid email/password combination'
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_path
  end

end

ii/ol/app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :require_valid_user!, except: [:destroy]
before_action :reset_session

	def show
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if@user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcome to the Sample App!"
			redirect_to user_path(@user);
		else
			render 'new'
		end
	end

	private

		def user_params
	      params.require(:user).permit(:name, :email, :password,
	                                   :password_confirmation)
	    end
end

ii/ol/app/helpers/accueil_helper.rb
module AccueilHelper
end

ii/ol/app/helpers/application_helper.rb
module ApplicationHelper

	def logged_in?
		!session[:user_id].nil?
	end
end

ii/ol/app/helpers/session_helper.rb
module SessionHelper

	# Logs in the given user.
	  def log_in(user)
	    session[:user_id] = user.id
	  end

	  # Remembers a user in a persistent session.
	  def remember(user)
	    user.remember
	    cookies.permanent.signed[:user_id] = user.id
	    cookies.permanent[:remember_token] = user.remember_token
	  end

	  # Returns true if the given user is the current user.
	  def current_user?(user)
	    user == current_user
	  end

	  # Returns the user corresponding to the remember token cookie.
	  def current_user
	  	@current_user ||= User.find_by(id: session[:user_id])
	  end

end

ii/ol/app/helpers/users_helper.rb
module UsersHelper
end

ii/ol/app/views/accueil/about.html.erb
<h1>Accueil#about</h1>
<p>Find me in app/views/accueil/about.html.erb</p>

ii/ol/app/views/accueil/agents.html.erb
<h1>Accueil#agents</h1>
<p>Find me in app/views/accueil/agents.html.erb</p>

ii/ol/app/views/accueil/auctions.html.erb
<h1>Accueil#auctions</h1>
<p>Find me in app/views/accueil/auctions.html.erb</p>

ii/ol/app/views/accueil/index.html.erb
<div class="">
        
        <div id="search-filter-container" class="container-fluid">
          
          <div id="search-filter" class="col-md-10">
            
            <!-- class="col-md-10 col-md-offset-1" -->
            
            <div id="search-filter-header-text">
              <h3 class="text-white">Discover your next property here.</h3>
            </div>
            
            <div id="search-filter-form-container">
              
              <form class="form">
                <div class="row">
                  
                  <div class="col-md-6">
                    <div class="form-group">
                      <input class="input-lg form-control" id="location" type="text" placeholder="Location">
                    </div>
                  </div>
                  
                  <div class="col-md-3">
                    <div class="form-group">
                      <input class="input-lg form-control" id="search-radius" type="text" placeholder="Search radius">
                    </div>
                  </div>
                  
                  <div class="col-md-3">
                    <div class="form-group">
                      <input class="input-lg form-control" id="property-type" type="text" placeholder="Property type">
                    </div>
                  </div>
                  
                </div>
                
                <div class="row">
                  
                  <div class="col-md-2">
                    <div class="form-group">
                      <input class="input-lg form-control" id="search-radius" type="text" placeholder="Search radius">
                    </div>
                  </div>
                  
                  <div class="col-md-2">
                    <div class="form-group">
                      <input class="input-lg form-control" id="search-radius" type="text" placeholder="Search radius">
                    </div>
                  </div>
                  
                  <div class="col-md-2">
                    <div class="form-group">
                      <input class="input-lg form-control" id="search-radius" type="text" placeholder="Search radius">
                    </div>
                  </div>
                  
                  <div class="col-md-3">
                    <div class="form-group">
                      <input class="input-lg form-control" id="search-radius" type="text" placeholder="Search radius">
                    </div>
                  </div>
                  
                  <div class="col-md-3">
                    <div class="form-group">
                      <button type="button" class="input-lg btn btn-default form-control button-submit"><i class=""></i> Search</button>
                    </div>
                  </div>
                  
                </div>
              </form>
              
            </div>
          </div>
          
        </div>
        
        <div id="marketing-message">
          <div class="container-fluid">
            <div class="col-md-12 text-center">
              <h3>Property Buying and Selling can be Stress-Free!</h3>
              <hr class="small-horizontal-line" />
              <br/>
              <div>
                <p>
                  Curabitur elementum urna eget eros iaculis ultricies. Integer dictum orci sed ligula pellentesque, vel fermentum leo finibus.</br>
                  Sed iaculis sapien egestas, mollis augue egestas, dapibus erat. Suspendisse porta sapien velit, eu auctor felis rutrum ut.</br>
                  Maecenas maximus tellus nulla, in finibus lacus imperdiet vel. Suspendisse pellentesque consectetur vehicula.</br>
                </p>
              </div>
          </div>
          </div>
        </div>
        
        <div id="property-categories">
          
          <div class="container-fluid">
            
              <div class="row">
              
                <div id="property-categorie-un" class="col-md-6 property-category no-padding">
                  <a class="property-category-link" href="">
                    <div class="property-category-overlay">
                      <div class="property-category-overlay-text-container">
                        <span class="property-category-overlay-description">RESIDENTIAL</span>
                      </div>
                    </div>
                  </a>
                </div>
         
                <div id="property-categorie-deux" class="col-md-6 property-category no-padding">
                  <a class="property-category-link" href="">
                    <div class="property-category-overlay">
                      <div class="property-category-overlay-text-container">
                        <span class="property-category-overlay-description">COMMERCIAL</span>
                      </div>
                    </div>
                  </a>
                </div>
                
                <div id="property-categorie-trois" class="col-md-6 property-category no-padding">
                  <a class="property-category-link" href="">
                    <div class="property-category-overlay">
                      <div class="property-category-overlay-text-container">
                        <span class="property-category-overlay-description">HOW IT WORKS?</span>
                      </div>
                    </div>
                  </a>
                </div>
                
                <div id="property-categorie-quatre" class="col-md-6 property-category no-padding">
                  <a class="property-category-link" href="">
                    <div class="property-category-overlay">
                      <div class="property-category-overlay-text-container">
                        <span class="property-category-overlay-description">SELL YOUR PROPERTY</span>
                      </div>
                    </div>
                  </a>
                </div>      
              
              </div>
            
          </div>
          
        </div>
        
        <div id="why-whoo-bid">
          
          <div class="container-fluid">
            <div class="row">
              <div class="container-md-12 text-center">
                <!-- -->
                <h3>Why Whoo Bid</h3>
                <hr class="small-horizontal-line" />
                  <br/>
                  <div class="row">
                    <div class="col-md-12">
                      <p>
                        Curabitur elementum urna eget eros iaculis ultricies. Integer dictum orci sed ligula pellentesque, vel fermentum leo finibus.</br>
                        Sed iaculis sapien egestas, mollis augue egestas, dapibus erat. Suspendisse porta sapien velit, eu auctor felis rutrum ut.</br>
                        Maecenas maximus tellus nulla, in finibus lacus imperdiet vel. Suspendisse pellentesque consectetur vehicula.</br>
                      </p>
                    </div>
                    
                    <div id="why-whoo-bid-item-container" class="col-md-12">
                      
                      <div class="row">
                        
                        <div class="col-md-3 why-whoo-bid-item">
                          <div class="why-whoo-bid-detail text-center">
                            <div class="why-whoo-bid-icon"><img src="icons/click.svg" class="why-whoo-bid-icon-img"/></div>
                            <div class="text">
                              <h4>
                                User friendly form
                              </h4>
                            </div>
                          </div>
                        </div>
                        
                        <div class="col-md-3 why-whoo-bid-item">
                          <div class="why-whoo-bid-detail text-center">
                            <div class="why-whoo-bid-icon"><img src="icons/gavel.svg" class="why-whoo-bid-icon-img"/></div>
                            <div class="text">
                              <h4>
                                Bringing the auctions to you
                              </h4>
                            </div>
                          </div>
                        </div>
                        
                        <div class="col-md-3 why-whoo-bid-item">
                          <div class="why-whoo-bid-detail text-center">
                            <div class="why-whoo-bid-icon"><img src="icons/tag.svg" class="why-whoo-bid-icon-img"/></div>
                            <div class="text">
                              <h4>
                                Innovating an out-of-date method of sale
                              </h4>
                            </div>
                          </div>
                        </div>
                        
                        <div class="col-md-3 why-whoo-bid-item">
                          <div class="why-whoo-bid-detail text-center">
                            <div class="why-whoo-bid-icon"><img src="icons/hand_shake.svg" class="why-whoo-bid-icon-img"/></div>
                            <div class="text">
                              <h4>
                                Fair independent service for both buyers and sellers
                              </h4>
                            </div>
                          </div>
                        </div>
                        
                      </div>
                    </div>
                  </div>
                <!-- -->
              </div>
            </div>
          </div>
          
        </div>
        
</div>

ii/ol/app/views/accueil/reviews.html.erb
<h1>Accueil#reviews</h1>
<p>Find me in app/views/accueil/reviews.html.erb</p>

ii/ol/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whoobid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Header -->
    <div class="container-fluid">
    
      <div id="header" class="col-md-12">
        
        <div class="row">
          
          <div id="cookies-flash" class="col-md-12 text-center">
            <span></span>
          </div>

          <% if notice %><div class="alert alert-info"><%= notice %></div><% end %> 

          <% if alert %><div class="alert alert-warning"><%= alert %></div><% end %> 

          <% if flash %>
          <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <% end %>
          
          <div id="head" class="col-md-12">
            <div class="row">
              
              <div id="logo" class="col-md-2 col-md-offset-2">
                <div>
                  <span>Whoobid</span>
                </div>
              </div>
              
              <div id="navigation" class="col-md-6 col-md-offset-2">
                <ul class="navigation-menu">
                  <li><%= link_to "HOME", root_path %></a></li>
                  <li><a href="#">AUCTIONS</a></li>
                  <li><a href="#">AGENTS</a></li>
                  <li><a href="#">REVIEWS</a></li>
                  <li><a href="#">ABOUT</a></li>

                  <% if logged_in? %>
                  <li class="menu-sign-in text-center"><%= link_to 'PROFILE', '#' %></li>
                  <li class="menu-sign-in text-center"><%= link_to 'LOG OUT', session_destroy_path, method: :delete %></li>
                  <% else %>
                  <li class="menu-sign-in text-center"><%= link_to 'SIGN IN', new_user_path %></li>
                  <% end %>

                  <li><a href="#"><i class="fas fa-search fa-lg"></i></a></li>
                </ul>
              </div>
              
              <!--
              <div id="profile-search-bar">
                
              </div>
              -->
              
            </div>
          </div>
          
        </div>
      </div>

    </div>
    <!-- End Header -->


    <!-- Yield -->
    <div id="content">

    <%= yield %>
    
    </div>
    <!-- End Yield -->

    <!-- Footer -->
    <div class="container-fluid no-padding"> 
    <div id="footer" class="col-md-12">
      
      <div class="row">
        
        <div id="footer-top" class="col-md-12">
          
          <div class="row">
            
            <div id="footer-about" class="col-md-4">
              <div class="footer-title-container">
              <h4 class="footer-title">ABOUT US</h4>
              </div>
              
              <p>
                Curabitur elementum urna eget eros iaculis ultricies. Integer dictum orci sed ligula pellentesque, vel fermentum leo finibus.</br>
                Sed iaculis sapien egestas, mollis augue egestas, dapibus erat. Suspendisse porta sapien velit, eu auctor felis rutrum ut.</br>
                Maecenas maximus tellus nulla, in finibus lacus imperdiet vel. Suspendisse pellentesque consectetur vehicula.</br>
                Pellentesque vel mauris commodo ante sagittis volutpat. Sed est sapien, mattis ut velit nec, tempor convallis sapien. Suspendisse vitae odio eget nulla cursus posuere nec at mi.</br>
                Proin fermentum semper odio, et congue lectus vehicula nec. Morbi tellus metus, eleifend vitae consequat sit amet, dictum at eros.</br>
              </p>
            </div>
            
            <div id="footer-gallery" class="col-md-6 col-md-offset-2">
              <div class="footer-title-container">
              <h4 class="footer-title">MY PHOTO STREAM</h4>
              </div>
              <div class="footer-gallery-photo">
                <div class="row">
                  <div class="footer-gallery-photo-element col-md-2">
                    <%= link_to image_tag('h.jpg', :class => 'img-responsive'), '#' %>
                  </div>
                  
                  <div class="footer-gallery-photo-element col-md-2">
                    <%= link_to image_tag('h.jpg', :class => 'img-responsive'), '#' %>
                  </div>
                  
                  <div class="footer-gallery-photo-element col-md-2">
                    <%= link_to image_tag('h.jpg', :class => 'img-responsive'), '#' %>
                  </div>
                  
                  <div class="footer-gallery-photo-element col-md-2">
                    <%= link_to image_tag('h.jpg', :class => 'img-responsive'), '#' %>
                  </div>
                  
                  <div class="footer-gallery-photo-element col-md-2">
                    <%= link_to image_tag('h.jpg', :class => 'img-responsive'), '#' %>
                  </div>
                  
                </div>
              </div>
              
              <div class="footer-gallery-photo">
                <div class="row">
                  <div class="footer-gallery-photo-element col-md-2">
                    <%= link_to image_tag('h.jpg', :class => 'img-responsive'), '#' %>
                  </div>
                  
                  <div class="footer-gallery-photo-element col-md-2">
                    <%= link_to image_tag('h.jpg', :class => 'img-responsive'), '#' %>
                  </div>
                  
                  <div class="footer-gallery-photo-element col-md-2">
                    <%= link_to image_tag('h.jpg', :class => 'img-responsive'), '#' %>
                  </div>
                  
                  <div class="footer-gallery-photo-element col-md-2">
                    <%= link_to image_tag('h.jpg', :class => 'img-responsive'), '#' %>
                  </div>
                  
                  <div class="footer-gallery-photo-element col-md-2">
                    <%= link_to image_tag('h.jpg', :class => 'img-responsive'), '#' %>
                  </div>
                  
                </div>
              </div>
              
            </div>
            
          </div>
          
        </div>
        
        <!-- -->
        
        <div id="footer-navigation-sn" class="col-md-12">
          
          <div class="row">
            
            <div id="footer-navigation" class="col-md-4">
              <ul class="footer-navigation-menu">
                <li><a href="#">HOME</a></li>
                <li><a href="#">AUCTIONS</a></li>
                <li><a href="#">AGENTS</a></li>
                <li><a href="#">REVIEWS</a></li>
                <li><a href="#">ABOUT</a></li>
              </ul>
            </div>
            
            <div id="footer-social-network" class="col-md-6 col-md-offset-2">
              <div class="col-md-10">
                <ul class="footer-navigation-sn-menu pull-right">
                  <li><a href="#"><span class="skype"><i class="fab fa-skype fa-lg"></i></span></a></li>
                  <li><a href="#"><span class="facebook"><i class="fab fa-facebook-f fa-lg"></i></span></a></li>
                  <li><a href="#"><span class="google-plus"><i class="fab fa-google-plus-g fa-lg"></i></span></a></li>
                  <li><a href="#"><span class="youtube"><i class="fab fa-youtube fa-lg"></i></span></a></li>
                  <li><a href="#"><span class="linkedin"><i class="fab fa-linkedin-in fa-lg"></i></span></a></li>
                </ul>
              </div>
            </div>
            
          </div>
          
        </div>
        
      </div>
      
    </div>
    <!-- End Footer -->
    
  </div>
  </body>
</html>

ii/ol/app/views/layouts/for_nav.html.erb
<% #if user_signed_in? %>
                  <li><%= #link_to 'PROFILE', "#" %></li>
                  <li><%= #link_to 'LOG OUT', destroy_user_session_path, method: :delete %></li>
                  <% #else %>

ii/ol/app/views/session/login.html.erb
<h1>Session#login</h1>
<p>Find me in app/views/session/login.html.erb</p>

ii/ol/app/views/session/logout.html.erb
<h1>Session#logout</h1>
<p>Find me in app/views/session/logout.html.erb</p>

ii/ol/app/views/users/_company_registration.html.erb
<form class="form">
                            
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="fname" placeholder="First Name*" />
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="fname" placeholder="First Name*" />
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="fname" placeholder="First Name*" />
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="fname" placeholder="First Name*" />
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="fname" placeholder="First Name*" />
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="fname" placeholder="First Name*" />
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-md-12 text-center">
                                        <h4>Not in the UK?</h4>
                                        <p>
                                            If you are not a UK resident please contact our auction team to discuss your options.
                                        </p>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="fname" placeholder="First Name*" />
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="fname" placeholder="First Name*" />
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-md-12 text-center">
                                        <p>
                                            How do you intend to fund the purchase?
                                        </p>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="fname" placeholder="First Name*" />
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-md-12 text-center">
                                        <p>
                                            The password entered must be at least 8 characters in length and contain an uppercase letter, a lowercase letter, a digit and a special character.
                                        </p>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="fname" placeholder="First Name*" />
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="fname" placeholder="First Name*" />
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="fname" placeholder="First Name*" />
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="fname" placeholder="First Name*" />
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <input type="submit" class="form-control" value="REGISTER"/>
                                        </div>
                                    </div>
                                </div>
        
                            </form>

ii/ol/app/views/users/_login.html.erb
<%= form_tag(session_create_path, {class:"form"}) do |f| %>

<div class="form-group">
     <%= email_field_tag(:email, params[:email], {class:"form-control", placeholder:"Email"}) %>
</div>

<div class="form-group">
<%= password_field_tag :password, params[:password], {class:"form-control", placeholder:"Password", autocomplete: "off"} %>
</div>


<div class="form-group">
  <%= check_box_tag :remember_me, class:"login-registration-checkboxl" %>
  <%= label_tag :remember_me %>
</div>

<div class="form-group">
    <%= check_box_tag :remember_me, class:"login-registration-checkbox" %>
    <%= label_tag :remember_me, 'I agree to a soft anti-mone laundering check' %>
</div>

<div class="form-group">
    <%= submit_tag "SIGN IN", class:"form-control" %>
</div>

<div class="row">
    <div class="col-md-6">
        <span><a href="#">Forgot your password?</a></span>
    </div>
                                
    <div class="col-md-6">
        <span><a href="#">Having trouble loging in?</a></span>
    </div>
</div>

<% end %>