config/routes.rb
Rails.application.routes.draw do
  root 'accueil#index'
  post 'session/create'
  delete 'session/destroy'
  get 'accueil/index'
  get 'accueil/auctions'
  get 'accueil/agents'
  get 'accueil/reviews'
  get 'accueil/about'

  #Users controller
  #get 'users/new', :as => "new_users"

  resources :users

  resources :users do
    resources :auctions
  end

  resources :users do
    resources :identities, only: [:new, :create, :show]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/auction.rb
class Auction < ApplicationRecord

	#mount_uploader :attachment, AttachmentUploader # Uploader for this model
	mount_uploader :brochure, BrochureUploader # Uploader for this model
	mount_uploader :vendor_id, VendorIdUploader # Uploader for this model
	mount_uploader :auction_pack, AuctionPackUploader # Uploader for this model
	#Association
	belongs_to :user
	has_one :photo, dependent: :destroy
	accepts_nested_attributes_for :photo
end

app/models/identity.rb
class Identity < ApplicationRecord

	#association
	belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord

	mount_uploader :main_photo, MainPhotoUploader # Uploader for this model
	mount_uploader :second_photo, SecondPhotoUploader # Uploader for this model
	mount_uploader :third_photo, ThirdPhotoUploader # Uploader for this model
	mount_uploader :fourth_photo, FourthPhotoUploader # Uploader for this model
	#Association
	belongs_to :auction
end

app/models/user.rb
class User < ApplicationRecord

  #Associations
  has_many :auctions, dependent: :destroy
  has_one :identity, dependent: :destroy
  #Validation
	before_save { self.email = email.downcase }
  	#validates :name, presence: true, length: { maximum: 50 }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
	has_secure_password
  	validates :email, uniqueness: true, presence: true
  	#enum role: [:client => 0, :agent => 1, :admin => 2]
  	enum role: [:client, :agent, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  	before_action :require_valid_user!

	  def current_user
	    if !session[:user_id].blank?
	      @user ||= User.find(session[:user_id])
	    end
	  end

	  def require_valid_user!
	    if current_user.nil?
	      flash[:error] = 'You must be logged in to access that page!'
	      redirect_to new_user_path
	    end
	  end

	  private

	  	#def role_template
		  #user_role = current_user.has_role? :client ? 'client' : 'operator'
		 # current_user = User.find(session[:user_id])
		#	if current_user.agent?
		#		user_role = "agent"
		#	elsif current_user.client?
		#		user_role = "client"
		#	elsif current_user.admin?
		#		user_role = "admin"
		#	end
		#
		 # "#{user_role}_#{action_name}"
		#end

		def role_template
		 #user_role = current_user.has_role? :client ? 'client' : 'operator'
		 user_role = current_user.role
		 "#{user_role}_#{action_name}"
		end

end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

	def index
		@auctions = Auction.all
	end

	def show
	end

	def new
		@user = current_user
		@auction = @user.auctions.new
		@auction.build_photo
	end

	def create
		@user = current_user
		@auction = @user.auctions.new(auction_params)
		if @auction.save
			flash[:success] = "Auction created!"
			redirect_to user_path(current_user.id);
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:user_id])
		@auction = @user.auctions.find(params[:id])
	end

	def update
		@user = User.find(params[:user_id])
		@auction = @user.auctions.find(params[:id])
	    if @auction.update_attributes(auction_update_params)
	      flash[:success] = "Auction Updated With Success"
	      redirect_to user_auctions_path(@user.id)
	    else
	      render 'edit'
	    end
	end

	def destroy
		@user = User.find(params[:user_id])
		@auction = @user.auctions.find(params[:id])
		if !@auction.photo.nil?
			@auction.photo.remove_main_photo
			@auction.photo.remove_second_photo
			@auction.photo.remove_third_photo
			@auction.photo.remove_fourth_photo
			@auction.destroy
			flash[:success] = "Auction Deleted With Success"
	      	redirect_to user_auctions_path(@user.id)
	    else
	    	@auction.destroy
	    	flash[:success] = "Auction Deleted With Success"
	      	redirect_to user_auctions_path(@user.id)
	     end

	end

	private
		def auction_params
			#params.require(:auction).permit(:first_name, :last_name, :title, :dob, :postcode, :telephone, :payment, :email, :password,
	                                   #:password_confirmation, :role, :company_name, :office_number)
	        params.require(:auction).permit(:address, :vendor_name, :contact,
	        	:email, :property_type, :tenure, :auction_date_time,
	        	:auction_method, :reserve_price, :starting_price,
	        	:key_features, :property_description, :brochure, :vendor_id,
	        	:auction_pack,
	        	:photo_attributes => [:id, :main_photo, :second_photo, :third_photo, :fourth_photo, :_delete])
		end

		#def auction_params
		#	params.require(:auction).permit!
		#end

		def auction_update_params
	        params.require(:auction).permit(:address, :vendor_name, :contact,
	        	:email, :property_type, :tenure, :auction_date_time,
	        	:auction_method, :reserve_price, :starting_price,
	        	:key_features, :property_description)
		end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController

	def show
	end

	def new
		@user = User.find(params[:user_id])
		@identity = @user.build_identity
	end

	def create
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :require_valid_user!, except: [:destroy]
before_action :reset_session, except: [:show, :edit, :update]

	def show
    	@user = User.find(params[:id])
    	render role_template
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if@user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcome to Whoobid!"
			redirect_to user_path(@user);
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
		render role_template
	end

	def update
		@user = User.find(params[:id])
		if @user.client?
			if @user.update_attributes(client_password_params)
				flash[:success] = "Client Password Successfully Updated"
				redirect_to user_path
			else
				render 'edit'
			end
		elsif @user.agent?
		    if @user.update_attributes(user_update_params)
		      flash[:success] = "Company Profile Updated With Success"
		      redirect_to edit_user_path
		    else
		      render 'edit'
		    end
		end
	end

	private

		def user_params
	      params.require(:user).permit(:first_name, :last_name, :title, :dob, :postcode, :telephone, :payment, :email, :password,
	                                   :password_confirmation, :role, :company_name, :office_number)
	    end

	    def user_update_params
	      params.require(:user).permit(:last_name, :address, :telephone, :email, :company_name, :office_number)
	    end

	    def client_password_params
	    	params.require(:user).permit(:password)
	    end
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/views/identities/_form.html.erb
<%= form_for @identity, :url => user_identities_path(current_user.id), :html => {class: "form"} do |f| %>
                                <div class="row">
                                    <div class="col-md-4">
                                      <%= f.label :name, "Name" %>
                                      <div class="form-group">
                                        <%= f.text_field :name, class:"form-control", placeholder:"" %>
                                      </div>
                                    </div>

                                    <div class="col-md-8">
                                      <%= f.label :address, "Adress" %>
                                      <div class="form-group">
                                        <%= f.text_field :adress, class:"form-control", placeholder:"" %>
                                      </div>
                                    </div>
                                </div>

                                

                                <div class="row">
                                    <div class="col-md-2">
                                      <%= f.label :dob, "DOB" %>
                                        <div class="form-group">
                                          <%= f.date_field :dob, class:"form-control"%>
                                        </div>
                                    </div>

                                    <div class="col-md-3">
                                      <%= f.label :id_number, "ID Number" %>
                                        <div class="form-group">
                                          <%= f.text_field :id_number, class:"form-control", placeholder:"" %>
                                        </div>
                                    </div>

                                    <div class="col-md-3">
                                      <%= f.label :document, "Upload Verified Document" %>
                                        <div class="form-group">
                                          <%= f.file_field :document, class:"form-control" %>
                                        </div>
                                    </div>

                                    <div class="col-md-4">
                                      <%= f.label :address_proof, "Proof of Address" %>
                                        <div class="form-group">
                                          <%= f.file_field :adress_proof, class:"form-control" %>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                  <div class="col-md-12">
                                    
                                  </div>
                                </div>

                                <div class="row">
                                  <div class="col-md-2 col-md-offset-10">
                                    <div class="form-group">
                                      <%= f.submit "SAVE", :class => "form-control" %>
                                    </div>
                                  </div>
                                </div>
<% end %>

app/views/identities/new.html.erb
<div class="container">
        <hr/>
        
        <div class="row">
            
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <h4>Your Account</h4>
                    </div>
                    
                    <div id="profile-menu" class="col-md-12">
                        <ul class="profile-navigation">
                            <li><%= link_to "Profile", user_path(current_user.id) %></li>
                            <li><%= link_to "Identity Verification", new_user_identity_path(current_user.id) %></li>
                            <li><a href="#">Payment Details</a></li>
                            <li><a href="#">Solicitor Details</a></li>
                            <li><a href="#">Current/Previous Bids</a></li>
                            <li><a href="#">Watchlist</a></li>
                        </ul>
                    <hr/>
                    </div>
                </div>
            </div>
            
            <div id="client-password-change" class="col-md-12">
                <div class="row">

                    <div class="col-md-12">
                        <%= render 'form' %>
                    </div>
                
                </div>
                
                <hr/>
            </div>
            
            
        </div>
      </div>

app/views/users/_client_password_change.html.erb
<%= form_for @user, :method => :put, :html => {class: "form"} do |f| %>
                                <div class="row">
                                    <div class="col-md-6">
                                      <div class="form-group">
                                        <%= f.password_field :password, class:"form-control", placeholder:"New Password*", autocomplete: "off" %>
                                      </div>
                                    </div>

                                    <div class="col-md-6">
                                      <div class="form-group">
                                        <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Password Confirmation*", autocomplete: "off" %>
                                      </div>
                                    </div>
                                </div>

                                

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                          <%= f.submit "UPDATE PASSWORD", class:"form-control" %>
                                        </div>
                                    </div>
                                </div>
<% end %>

app/views/users/client_edit.html.erb
<div class="container">
        <hr/>
        
        <div class="row">
            
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <h4>Your Account</h4>
                    </div>
                    
                    <div id="profile-menu" class="col-md-12">
                        <ul class="profile-navigation">
                            <li><%= link_to "Profile", user_path(current_user.id) %></li>
                            <li><%= link_to "Identity Verification", new_user_identity_path(current_user.id) %></li>
                            <li><a href="#">Payment Details</a></li>
                            <li><a href="#">Solicitor Details</a></li>
                            <li><a href="#">Current/Previous Bids</a></li>
                            <li><a href="#">Watchlist</a></li>
                        </ul>
                    <hr/>
                    </div>
                </div>
            </div>
            
            <div id="client-password-change" class="col-md-12">
                <div class="row">
                    
                    <div class="col-md-12">
                        <h4>Password Reset</h4>
                        <br/>
                    </div>

                    <div class="col-md-12">
                        <%= render 'client_password_change' %>
                    </div>
                
                </div>
                
                <hr/>
            </div>
            
            
        </div>
      </div>

app/views/users/client_show.html.erb
<div class="container">
        <hr/>
        
        <div class="row">
            
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <h4>Your Account</h4>
                    </div>
                    
                    <div id="profile-menu" class="col-md-12">
                        <ul class="profile-navigation">
                            <li><%= link_to "Profile", user_path(current_user.id) %></li>
                            <li><%= link_to "Identity Verification", new_user_identity_path(current_user.id) %></li>
                            <li><a href="#">Payment Details</a></li>
                            <li><a href="#">Solicitor Details</a></li>
                            <li><a href="#">Current/Previous Bids</a></li>
                            <li><a href="#">Watchlist</a></li>
                        </ul>
                    <hr/>
                    </div>
                </div>
            </div>
            
            <div id="profile-infos" class="col-md-12">
                <div class="row">
                    <div class="col-md-2">
                        <h4 class="profile-header">Name</h4>
                        <p><%= user_name %></p>
                    </div>
                    
                    <div class="col-md-5">
                        <div class="col-md-6">
                            <h4 class="profile-header">Email</h4>
                            <p><%= current_user.email %></p>
                        </div>
                        <div class="col-md-6">
                            <button class="btn btn-default profile-button">Resend Verification</button>
                        </div>
                    </div>
                    
                    <div class="col-md-5">
                        <div class="col-md-6">
                            <h4>Password</h4>
                            <p><span class="dot"></span><span class="dot"></span><span class="dot"></span><span class="dot"></span><span class="dot"></span><span class="dot"></span><span class="dot"></span><span class="dot"></span><span class="dot"></span><span class="dot"></span></p>
                        </div>
                        <div class="col-md-6">
                            <%= link_to "Reset Password", edit_user_path(current_user.id), :class => "btn btn-default profile-button" %>
                        </div>
                    </div>
                </div>
                
                <hr/>
            </div>
            
            
            <div class="col-md-12 last-profile-section">
                <h4>Marketing preferences</h4>
                <div class="row">
                    <form class="form">
                        <div class="col-md-6">
                            
                            <div class="row">
                                <div class="col-md-12">
                                    <h4 class="profile-header">Email</h4>
                                    <p>I'd like to receive email updates for the following</p>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-8">
                                            <p>1. Properties available by online auctions</p>
                                        </div>
                                        <div class="col-md-4 form-group">
                                            <div class="col-md-6">
                                                <input type="radio" name="auction" value="true"> Yes<br>
                                            </div>
                                            <div class="col-md-6">
                                                <input type="radio" name="auction" value="false" checked> No<br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-8">
                                            <p>2. New features alert</p>
                                        </div>
                                        <div class="col-md-4 form-group">
                                            <div class="col-md-6">
                                                <input type="radio" name="new_feature" value="true"> Yes<br>
                                            </div>
                                            <div class="col-md-6">
                                                <input type="radio" name="new_feature" value="false" checked> No<br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-8">
                                            <p>3. New properties build for sale with our partners</p>
                                        </div>
                                        <div class="col-md-4 form-group">
                                            <div class="col-md-6">
                                                <input type="radio" name="new_property" value="true"> Yes<br>
                                            </div>
                                            <div class="col-md-6">
                                                <input type="radio" name="new_property" value="false" checked> No<br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-12">
                                    <h4 class="profile-header">Phone/SMS</h4>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-8">
                                            <p>I am happy to be contated by phone or SMS about properties I have shown an interst in.</p>
                                        </div>
                                        <div class="col-md-4 form-group">
                                            <div class="col-md-6">
                                                <input type="radio" name="property_interested_in" value="true"> Yes<br>
                                            </div>
                                            <div class="col-md-6">
                                                <input type="radio" name="property_interested_in" value="false" checked> No<br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-md-6 col-md-offset-6">
                                    <input type="submit" value="Save Changes" class="form-control profile-button"/>
                                </div>
                            </div>
                    </form>
                </div>
            </div>
            
        </div>
        
      </div>