ii/config/routes.rb
Rails.application.routes.draw do
  root 'accueil#index'
  post 'session/create'
  delete 'session/destroy'
  get 'accueil/index'
  get 'accueil/auctions'
  get 'accueil/agents'
  get 'accueil/reviews'
  get 'accueil/about'

  #Users controller
  #get 'users/new', :as => "new_users"

  resources :users

  resources :users do
  resources :auctions
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ii/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ii/app/models/auction.rb
class Auction < ApplicationRecord

	#Association
	belongs_to :user
end

ii/app/models/user.rb
class User < ApplicationRecord

  #Associations
  has_many :auctions, dependent: :destroy
  #Validation
	before_save { self.email = email.downcase }
  	#validates :name, presence: true, length: { maximum: 50 }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
	has_secure_password
  	validates :email, uniqueness: true, presence: true
  	#enum role: [:client => 0, :agent => 1, :admin => 2]
  	enum role: [:client, :agent, :admin]
end

ii/app/controllers/accueil_controller.rb
class AccueilController < ApplicationController
  skip_before_action :require_valid_user!

  def index
  end

  def auctions
  end

  def agents
  end

  def reviews
  end

  def about
  end
end

ii/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  	before_action :require_valid_user!

	  def current_user
	    if !session[:user_id].blank?
	      @user ||= User.find(session[:user_id])
	    end
	  end

	  def require_valid_user!
	    if current_user.nil?
	      flash[:error] = 'You must be logged in to access that page!'
	      redirect_to login_path
	    end
	  end

	  private

	  	#def role_template
		  #user_role = current_user.has_role? :client ? 'client' : 'operator'
		 # current_user = User.find(session[:user_id])
		#	if current_user.agent?
		#		user_role = "agent"
		#	elsif current_user.client?
		#		user_role = "client"
		#	elsif current_user.admin?
		#		user_role = "admin"
		#	end
		#
		 # "#{user_role}_#{action_name}"
		#end

		def role_template
		 #user_role = current_user.has_role? :client ? 'client' : 'operator'
		 user_role = current_user.role
		 "#{user_role}_#{action_name}"
		end

end

ii/app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

	def index
	end

	def show
	end

	def new
		@auction = Auction.new
	end

	def create
		@auction = Auction.new(auction_params)
		if @auction.save
			flash[:success] = "Auction created!"
			redirect_to user_path(current_user.id);
		else
			render 'new'
		end
	end

	def edit
	end

	def update
	end

	def destroy
	end

	private
		def auction_params
			#params.require(:auction).permit(:first_name, :last_name, :title, :dob, :postcode, :telephone, :payment, :email, :password,
	                                   #:password_confirmation, :role, :company_name, :office_number)
	        params.require(:auction).permit!
		end
end

ii/app/controllers/session_controller.rb
class SessionController < ApplicationController
skip_before_action :require_valid_user!, except: [:destroy]

  def create
    reset_session
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = 'Succesful login'
      redirect_to user_path(@user)
    else
      flash[:error] = 'Invalid email/password combination'
      redirect_to new_user_path
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_path
  end

end

ii/app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :require_valid_user!, except: [:destroy]
before_action :reset_session, except: [:show, :edit, :update]

	def show
    	@user = User.find(params[:id])
    	render role_template
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if@user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcome to Whoobid!"
			redirect_to user_path(@user);
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
		render role_template
	end

	def update
		@user = User.find(params[:id])
	    if @user.update_attributes(user_update_params)
	      flash[:success] = "Company Profile Updated With Success"
	      redirect_to edit_user_path
	    else
	      render 'edit'
	    end
	end

	private

		def user_params
	      params.require(:user).permit(:first_name, :last_name, :title, :dob, :postcode, :telephone, :payment, :email, :password,
	                                   :password_confirmation, :role, :company_name, :office_number)
	    end

	    def user_update_params
	      params.require(:user).permit(:last_name, :address, :telephone, :email, :company_name, :office_number)
	    end
end

ii/app/helpers/accueil_helper.rb
module AccueilHelper
end

ii/app/helpers/application_helper.rb
module ApplicationHelper

end

ii/app/helpers/auctions_helper.rb
module AuctionsHelper
end

ii/app/helpers/session_helper.rb
module SessionHelper

	def logged_in?
		!current_user.nil?
	end
	# Logs in the given user.
	  def log_in(user)
	    session[:user_id] = user.id
	  end

	  # Remembers a user in a persistent session.
	  def remember(user)
	    user.remember
	    cookies.permanent.signed[:user_id] = user.id
	    cookies.permanent[:remember_token] = user.remember_token
	  end

	  # Returns true if the given user is the current user.
	  def current_user?(user)
	    user == current_user
	  end

	  def user_name
	  	return "#{current_user.first_name} #{current_user.last_name}"
	  end
	  # Returns the user corresponding to the remember token cookie.
	  def current_user
	  	@current_user ||= User.find_by(id: session[:user_id])
	  end

end

ii/app/helpers/users_helper.rb
module UsersHelper
end

ii/app/views/accueil/about.html.erb
<h1>Accueil#about</h1>
<p>Find me in app/views/accueil/about.html.erb</p>

ii/app/views/accueil/agents.html.erb
<h1>Accueil#agents</h1>
<p>Find me in app/views/accueil/agents.html.erb</p>

ii/app/views/accueil/auctions.html.erb
<h1>Accueil#auctions</h1>
<p>Find me in app/views/accueil/auctions.html.erb</p>

ii/app/views/accueil/index.html.erb
<div class="">
        
        <div id="search-filter-container" class="container-fluid">
          
          <div id="search-filter" class="col-md-10">
            
            <!-- class="col-md-10 col-md-offset-1" -->
            
            <div id="search-filter-header-text">
              <h3 class="text-white">Discover your next property here.</h3>
            </div>
            
            <div id="search-filter-form-container">
              
              <form class="form">
                <div class="row">
                  
                  <div class="col-md-6">
                    <div class="form-group">
                      <input class="input-lg form-control" id="location" type="text" placeholder="Location">
                    </div>
                  </div>
                  
                  <div class="col-md-3">
                    <div class="form-group">
                      <input class="input-lg form-control" id="search-radius" type="text" placeholder="Search radius">
                    </div>
                  </div>
                  
                  <div class="col-md-3">
                    <div class="form-group">
                      <input class="input-lg form-control" id="property-type" type="text" placeholder="Property type">
                    </div>
                  </div>
                  
                </div>
                
                <div class="row">
                  
                  <div class="col-md-2">
                    <div class="form-group">
                      <input class="input-lg form-control" id="search-radius" type="text" placeholder="Search radius">
                    </div>
                  </div>
                  
                  <div class="col-md-2">
                    <div class="form-group">
                      <input class="input-lg form-control" id="search-radius" type="text" placeholder="Search radius">
                    </div>
                  </div>
                  
                  <div class="col-md-2">
                    <div class="form-group">
                      <input class="input-lg form-control" id="search-radius" type="text" placeholder="Search radius">
                    </div>
                  </div>
                  
                  <div class="col-md-3">
                    <div class="form-group">
                      <input class="input-lg form-control" id="search-radius" type="text" placeholder="Search radius">
                    </div>
                  </div>
                  
                  <div class="col-md-3">
                    <div class="form-group">
                      <button type="button" class="input-lg btn btn-default form-control button-submit"><i class=""></i> Search</button>
                    </div>
                  </div>
                  
                </div>
              </form>
              
            </div>
          </div>
          
        </div>
        
        <div id="marketing-message">
          <div class="container-fluid">
            <div class="col-md-12 text-center">
              <h3>Property Buying and Selling can be Stress-Free!</h3>
              <hr class="small-horizontal-line" />
              <br/>
              <div>
                <p>
                  Curabitur elementum urna eget eros iaculis ultricies. Integer dictum orci sed ligula pellentesque, vel fermentum leo finibus.</br>
                  Sed iaculis sapien egestas, mollis augue egestas, dapibus erat. Suspendisse porta sapien velit, eu auctor felis rutrum ut.</br>
                  Maecenas maximus tellus nulla, in finibus lacus imperdiet vel. Suspendisse pellentesque consectetur vehicula.</br>
                </p>
              </div>
          </div>
          </div>
        </div>
        
        <div id="property-categories">
          
          <div class="container-fluid">
            
              <div class="row">
              
                <div id="property-categorie-un" class="col-md-6 property-category no-padding">
                  <a class="property-category-link" href="">
                    <div class="property-category-overlay">
                      <div class="property-category-overlay-text-container">
                        <span class="property-category-overlay-description">RESIDENTIAL</span>
                      </div>
                    </div>
                  </a>
                </div>
         
                <div id="property-categorie-deux" class="col-md-6 property-category no-padding">
                  <a class="property-category-link" href="">
                    <div class="property-category-overlay">
                      <div class="property-category-overlay-text-container">
                        <span class="property-category-overlay-description">COMMERCIAL</span>
                      </div>
                    </div>
                  </a>
                </div>
                
                <div id="property-categorie-trois" class="col-md-6 property-category no-padding">
                  <a class="property-category-link" href="">
                    <div class="property-category-overlay">
                      <div class="property-category-overlay-text-container">
                        <span class="property-category-overlay-description">HOW IT WORKS?</span>
                      </div>
                    </div>
                  </a>
                </div>
                
                <div id="property-categorie-quatre" class="col-md-6 property-category no-padding">
                  <a class="property-category-link" href="">
                    <div class="property-category-overlay">
                      <div class="property-category-overlay-text-container">
                        <span class="property-category-overlay-description">SELL YOUR PROPERTY</span>
                      </div>
                    </div>
                  </a>
                </div>      
              
              </div>
            
          </div>
          
        </div>
        
        <div id="why-whoo-bid">
          
          <div class="container-fluid">
            <div class="row">
              <div class="container-md-12 text-center">
                <!-- -->
                <h3>Why Whoo Bid</h3>
                <hr class="small-horizontal-line" />
                  <br/>
                  <div class="row">
                    <div class="col-md-12">
                      <p>
                        Curabitur elementum urna eget eros iaculis ultricies. Integer dictum orci sed ligula pellentesque, vel fermentum leo finibus.</br>
                        Sed iaculis sapien egestas, mollis augue egestas, dapibus erat. Suspendisse porta sapien velit, eu auctor felis rutrum ut.</br>
                        Maecenas maximus tellus nulla, in finibus lacus imperdiet vel. Suspendisse pellentesque consectetur vehicula.</br>
                      </p>
                    </div>
                    
                    <div id="why-whoo-bid-item-container" class="col-md-12">
                      
                      <div class="row">
                        
                        <div class="col-md-3 why-whoo-bid-item">
                          <div class="why-whoo-bid-detail text-center">
                            <div class="why-whoo-bid-icon"><img src="icons/click.svg" class="why-whoo-bid-icon-img"/></div>
                            <div class="text">
                              <h4>
                                User friendly form
                              </h4>
                            </div>
                          </div>
                        </div>
                        
                        <div class="col-md-3 why-whoo-bid-item">
                          <div class="why-whoo-bid-detail text-center">
                            <div class="why-whoo-bid-icon"><img src="icons/gavel.svg" class="why-whoo-bid-icon-img"/></div>
                            <div class="text">
                              <h4>
                                Bringing the auctions to you
                              </h4>
                            </div>
                          </div>
                        </div>
                        
                        <div class="col-md-3 why-whoo-bid-item">
                          <div class="why-whoo-bid-detail text-center">
                            <div class="why-whoo-bid-icon"><img src="icons/tag.svg" class="why-whoo-bid-icon-img"/></div>
                            <div class="text">
                              <h4>
                                Innovating an out-of-date method of sale
                              </h4>
                            </div>
                          </div>
                        </div>
                        
                        <div class="col-md-3 why-whoo-bid-item">
                          <div class="why-whoo-bid-detail text-center">
                            <div class="why-whoo-bid-icon"><img src="icons/hand_shake.svg" class="why-whoo-bid-icon-img"/></div>
                            <div class="text">
                              <h4>
                                Fair independent service for both buyers and sellers
                              </h4>
                            </div>
                          </div>
                        </div>
                        
                      </div>
                    </div>
                  </div>
                <!-- -->
              </div>
            </div>
          </div>
          
        </div>
        
</div>

ii/app/views/accueil/reviews.html.erb
<h1>Accueil#reviews</h1>
<p>Find me in app/views/accueil/reviews.html.erb</p>

ii/app/views/auctions/new.html.erb
<div class="container">
        <hr/>
        
        <div class="row">
            
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <h4>Your Account</h4>
                    </div>
                    
                    <div id="profile-menu" class="col-md-12">
                        <%= render :partial => '/users/agent_menu' %>
                    <hr/>
                    </div>
                </div>
            </div>
            
            <div id="profile-infos" class="col-md-12 last-profile-section">
            <%= form_for @auction, :url => user_auctions_path(current_user.id), :html => {:class => 'form'} do |f| %>

                
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <%= f.label :address %>
                            <%= f.text_field :address, class:"form-control" %>
                        </div>
                    </div>
                </div>

                <div class="row">

                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :vendor_name, "Vendor's Full Name" %>
                            <%= f.text_field :vendor_name, class:"form-control" %>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :contact, "Contact Number" %>
                            <%= f.text_field :contact, class:"form-control" %>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :email, "Email" %>
                            <%= f.text_field :email, class:"form-control" %>
                        </div>
                    </div>
                </div>

                <!-- -->
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-2">
                                    <%= f.label :property_type_detached, "Detached" %>
                                    <%= f.radio_button :property_type, 'detached', class:"form-control" %>
                                </div>

                                <div class="col-md-2">
                                    <%= f.label :property_type_semi_detached, "Semi-Detached" %>
                                    <%= f.radio_button :property_type, 'semi_detached', class:"form-control" %>
                                </div>

                                <div class="col-md-2">
                                    <%= f.label :property_type_terrace, "Terrace" %>
                                    <%= f.radio_button :property_type, 'terrace', class:"form-control" %>
                                </div>

                                <div class="col-md-2">
                                    <%= f.label :property_type_flat, "Flat" %>
                                    <%= f.radio_button :property_type, 'flat', class:"form-control" %>
                                </div>

                                <div class="col-md-2">
                                    <%= f.label :property_type_land, "Land" %>
                                    <%= f.radio_button :property_type, 'land', class:"form-control" %>
                                </div>

                                <div class="col-md-2">
                                    <div class="form-group">
                                    <%= f.label :property_type_commercial, "Commercial" %>
                                    <%= f.radio_button :property_type, 'commercial', class:"form-control" %>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :tenure %>
                            <%= f.text_field :tenure, class:"form-control" %>
                        </div>
                    </div>
                </div>

                <!-- -->
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :auction_date_time, "Date & Time of Auction" %>
                            <%= f.text_field :auction_date_time, class:"form-control", placeholder:"Telephone Number*" %>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :auction_method, "Traditional or Moder method of Auction" %>
                            <%= f.check_box :auction_method, class:"form-control" %>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :reserve_price %>
                            <%= f.text_field :reserve_price, class:"form-control"%>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :starting_price, "Starting Price (For bidding)" %>
                            <%= f.text_field :starting_price, class:"form-control" %>
                        </div>
                    </div>

                    <div class="col-md-8">
                        <div class="form-group">
                            <%= f.label :key_features %>
                            <%= f.text_field :key_features, class:"form-control"%>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <%= f.label :property_description %>
                            <%= f.text_area :property_description, class:"form-control" %>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2 col-md-offset-10">
                        <div class="form-group">
                            <%= f.submit "Save Changes", class:"form-control btn btn-default" %>
                        </div>
                    </div>
                </div>

                <% end %>
            </div>
            
        </div>
        
      </div>

ii/app/views/auctions/no_new_from.html.erb
<div class="container">
        <hr/>
        
        <div class="row">
            
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <h4>Your Account</h4>
                    </div>
                    
                    <div id="profile-menu" class="col-md-12">
                        <%= render :partial => '/users/agent_menu' %>
                    <hr/>
                    </div>
                </div>
            </div>
            
            <div id="profile-infos" class="col-md-12 last-profile-section">
            <%= form_for @auction, :url => user_auctions_path(current_user.id), :html => {:class => 'form'} do |f| %>

                
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <%= f.label :address %>
                            <%= f.text_field :address, class:"form-control" %>
                        </div>
                    </div>
                </div>

                <div class="row">

                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :vendor_name, "Vendor's Full Name" %>
                            <%= f.text_field :vendor_name, class:"form-control" %>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :contact, "Contact Number" %>
                            <%= f.text_field :contact, class:"form-control" %>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :email, "Email" %>
                            <%= f.text_field :email, class:"form-control", placeholder:"Last Name*" %>
                        </div>
                    </div>
                </div>

                <!-- -->
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-2">
                                    <%= f.label :property_type_detached, "Detached" %>
                                    <%= f.radio_button :property_type, 'detached', class:"form-control" %>
                                </div>

                                <div class="col-md-2">
                                    <%= f.label :property_type_semi_detached, "Semi-Detached" %>
                                    <%= f.radio_button :property_type, 'semi_detached', class:"form-control" %>
                                </div>

                                <div class="col-md-2">
                                    <%= f.label :property_type_terrace, "Terrace" %>
                                    <%= f.radio_button :property_type, 'terrace', class:"form-control" %>
                                </div>

                                <div class="col-md-2">
                                    <%= f.label :property_type_flat, "Flat" %>
                                    <%= f.radio_button :property_type, 'flat', class:"form-control" %>
                                </div>

                                <div class="col-md-2">
                                    <%= f.label :property_type_land, "Land" %>
                                    <%= f.radio_button :property_type, 'land', class:"form-control" %>
                                </div>

                                <div class="col-md-2">
                                    <div class="form-group">
                                    <%= f.label :property_type_commercial, "Commercial" %>
                                    <%= f.radio_button :property_type, 'commercial', class:"form-control" %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :tenure %>
                            <%= f.text_field :tenure, class:"form-control" %>
                        </div>
                    </div>
                </div>

                <!-- -->
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :auction_date_time, "Date & Time of Auction" %>
                            <%= f.text_field :auction_date_time, class:"form-control", placeholder:"Telephone Number*" %>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :auction_method, "Traditional or Moder method of Auction" %>
                            <%= f.check_box :auction_method, class:"form-control" %>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :reserve_price %>
                            <%= f.text_field :reserve_price, class:"form-control"%>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :starting_price, "Starting Price (For bidding)" %>
                            <%= f.text_field :starting_price, class:"form-control" %>
                        </div>
                    </div>

                    <div class="col-md-8">
                        <div class="form-group">
                            <%= f.label :key_features %>
                            <%= f.text_field :key_features, class:"form-control"%>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <%= f.label :property_description %>
                            <%= f.text_area :property_description, class:"form-control" %>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2 col-md-offset-10">
                        <div class="form-group">
                            <%= f.submit "Save Changes", class:"form-control btn btn-default" %>
                        </div>
                    </div>
                </div>

                <% end %>
            </div>
            
        </div>
        
      </div>

ii/app/views/users/_agent_menu.html.erb
<ul class="profile-navigation">
    <li><%= link_to "Company Profile", edit_user_path(current_user.id) %></li>
    <li><%= link_to "Add/Edit or Remove Auction", new_user_auction_path(current_user.id) %></li>
    <li><a href="#">Your Auction Site</a></li>
    <li><a href="#">Auction Confirmation Details</a></li>
</ul>

ii/app/views/users/_login.html.erb
<%= form_tag(session_create_path, {class:"form"}) do |f| %>

<div class="form-group">
     <%= email_field_tag(:email, params[:email], {class:"form-control", placeholder:"Email"}) %>
</div>

<div class="form-group">
<%= password_field_tag :password, params[:password], {class:"form-control", placeholder:"Password", autocomplete: "off"} %>
</div>


<div class="form-group">
  <%= check_box_tag :remember_me, true, false, {class:"login-registration-checkbox"} %>
  <%= label_tag :remember_me %>
</div>

<div class="form-group">
    <%= check_box_tag :remember_me, true, false, {class:"login-registration-checkbox"} %>
    <%= label_tag :remember_me, 'I agree to a soft anti-mone laundering check' %>
</div>

<div class="form-group">
    <%= submit_tag "SIGN IN", class:"form-control" %>
</div>

<div class="row">
    <div class="col-md-6">
        <span><a href="#">Forgot your password?</a></span>
    </div>
                                
    <div class="col-md-6">
        <span><a href="#">Having trouble loging in?</a></span>
    </div>
</div>

<% end %>